export const SIGNIN_ISLOADING = 'SIGNIN_ISLOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP_ISLOADING = 'SIGNUP_ISLOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const VERIFY_ISLOADING = 'VERIFY_ISLOADING';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';

export const FORGOT_ISLOADING = 'FORGOT_ISLOADING';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILURE = 'FORGOT_FAILURE';

export const RESET_ISLOADING = 'RESET_ISLOADING';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

export const CLEAR_STATE = 'CLEAR_STATE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
