export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';
export const GET_CART_ISLOADING = 'GET_CART_ISLOADING';

export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILURE = 'DELETE_CART_FAILURE';
export const DELETE_CART_ISLOADING = 'DELETE_CART_ISLOADING';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const ADD_TO_CART_ISLOADING = 'ADD_TO_CART_ISLOADING';

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';
export const UPDATE_CART_ISLOADING = 'UPDATE_CART_ISLOADING';

export const ADD_CART_TO_DB_SUCCESS = 'ADD_CART_TO_DB_SUCCESS';
export const ADD_CART_TO_DB_FAILURE = 'ADD_CART_TO_DB_FAILURE';
export const ADD_CART_TO_DB_ISLOADING = 'ADD_CART_TO_DB_ISLOADING';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';