export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_ISLOADING = 'GET_CATEGORIES_ISLOADING';

export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';
export const CREATE_CATEGORY_ISLOADING = 'CREATE_CATEGORY_ISLOADING';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';