export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_ISLOADING = 'GET_PRODUCTS_ISLOADING';

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
export const CREATE_PRODUCT_ISLOADING = 'CREATE_PRODUCT_ISLOADING';

export const GET_PRODUCTS_TOTAL_SUCCESS = 'GET_PRODUCTS_TOTAL_SUCCESS';
export const GET_PRODUCTS_TOTAL_FAILURE = 'GET_PRODUCTS_TOTAL_FAILURE';
export const GET_PRODUCTS_TOTAL_ISLOADING = 'GET_PRODUCTS_TOTAL_ISLOADING';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';